/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2023-10-24 08:15:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.exercises;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exe04_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>User Info Page</title>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function checkRequired() {\r\n");
      out.write("            if (\r\n");
      out.write("                document.getElementById(\"name_id\").value == \"\" ||\r\n");
      out.write("                document.getElementById(\"password_id\").value == \"\" ||\r\n");
      out.write("                document.getElementById(\"age_id\").value == \"\" ||\r\n");
      out.write("                (document.getElementById(\"male_id\").checked == false && document.getElementById(\"female_id\").checked == false) ||\r\n");
      out.write("                document.getElementById(\"address_id\").value == \"\"\r\n");
      out.write("            ) {\r\n");
      out.write("                alert(\"All fields are required!!!\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .label{\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: #FF0000; \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <form action=\"exe04submit.jsp\" method=\"post\" onsubmit=\"return checkRequired();\">\r\n");
      out.write("        <label for=\"name\" class=\"label\">Name:</label>\r\n");
      out.write("        <input type=\"text\" id=\"name_id\" name=\"name_name\"><br><br>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"password\" class=\"label\">Password:</label>\r\n");
      out.write("        <input type=\"password\" id=\"password_id\" name=\"password_name\"><br><br>\r\n");
      out.write("        \r\n");
      out.write("        <label for=\"age\" class=\"label\">Age:</label>\r\n");
      out.write("        <input type=\"age\" id=\"age_id\" name=\"age_name\"><br><br>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"sex\" class=\"label\">Sex:</label>\r\n");
      out.write("        <input type=\"radio\" id=\"male_id\" name=\"sex_name\" value=\"male\">Male\r\n");
      out.write("        <input type=\"radio\" id=\"female_id\" name=\"sex_name\" value=\"female\">Female<br><br>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"address\" class=\"label\">Address:</label>\r\n");
      out.write("        <textarea name=\"address_name\" id=\"address_id\" rows=\"4\" cols=\"50\" placeholder=\"Enter your address\"></textarea><br><br>\r\n");
      out.write("\r\n");
      out.write("        <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
