/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2023-08-25 07:50:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Display_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"/js/script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form style=\"height:70% ; width:90%; margin-top:8%; margin-left:5%; display:none\" id=\"divform\">\r\n");
      out.write("<label for=\"ename\" style=\"margin-button:5%\">Employee Name: </label>\r\n");
      out.write("<input type=\"text\" name=\"ename\" id=\"ename\"style=\"margin-button:5% ; width:40%;height:8%\" />\r\n");
      out.write("<br>\r\n");
      out.write("<label for=\"eaddress\" style=\"margin-button:5%\">Employee Address: </label>\r\n");
      out.write("<input type=\"text\" name=\"eaddress\" id=\"eaddress\" style=\"margin-button:5%; width:40%;height:8%\" />\r\n");
      out.write("<br>\r\n");
      out.write("<label for=\"ephone\" style=\"margin-button:5%\">Employee Phone Number: </label>\r\n");
      out.write("<input type=\"text\" name=\"ephone\" id=\"ephone\" style=\"margin-button:5%; width:40%;height:8%\" />\r\n");
      out.write("<br>\r\n");
      out.write("<label for=\"eage\"style=\"margin-button:5%\" >Employee Age: </label>\r\n");
      out.write("<input type=\"text\" name=\"eage\" id=\"eage\" style=\"margin-button:5%; width:40%;height:8%\" />\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"button\" name=\"save\" id=\"save\" style=\"margin-button:5%; width:40%;height:8%\" value=\"save\" onclick=\"onSave()\"/>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
