/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2023-08-25 13:46:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Employees_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"/js/script.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function onAdd()\r\n");
      out.write("{\r\n");
      out.write("\talert(\"---------onAdd---------\");\r\n");
      out.write("    var form      = document.getElementById(\"divform\");\r\n");
      out.write("\tform.style.display = \"inline-block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("td{\r\n");
      out.write("\tborder-style: solid;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("\twidth:90%;\r\n");
      out.write("\tmargin:0 5%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"table\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t    <td>Select</td>\r\n");
      out.write("\t\t\t<td>Employee Id</td>\r\n");
      out.write("\t\t\t<td>Employee Name</td>\r\n");
      out.write("\t\t\t<td>Employee Address</td>\r\n");
      out.write("\t\t\t<td>Employee Phone Number</td>\r\n");
      out.write("\t\t\t<td>Employee Age</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t    <td><input type=\"radio\" class=\"radio\" name=\"0\" onChange=\"onChange()\"/></td>\r\n");
      out.write("\t\t\t<td id=\"1\" >1</td>\r\n");
      out.write("\t\t\t<td id=\"2\">George Chalfoun</td>\r\n");
      out.write("\t\t\t<td name=\"address\">Bsarma</td>\r\n");
      out.write("\t\t\t<td name=\"phone\">70199887</td>\r\n");
      out.write("\t\t\t<td name=\"age\">26</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("            <td><input type=\"radio\" class=\"radio\" name=\"0\" onChange=\"onChange()\"/></td>\r\n");
      out.write("\t\t\t<td id = \"1\"> 2 </td>\r\n");
      out.write("\t\t\t<td id=\"2\">Joseph Khawly</td>\r\n");
      out.write("\t\t\t<td name=\"address\">Kfar Aaqa</td>\r\n");
      out.write("\t\t\t<td name=\"phone\">71009765</td>\r\n");
      out.write("\t\t\t<td name=\"age\">22</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"button\" id=\"add\" name=\"add\" style=\"margin-top:1%;width:8%;height:6%\" value=\"Add\" onclick=\"onAdd()\"/>\r\n");
      out.write("\t<input type=\"button\" id=\"Modify\" name=\"Modify\" style=\"margin-top:1%; margin-left:2% ; width:8%;height:6%\" value=\"Modify\" onclick=\"onModify()\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form style=\"height:70% ; width:90%; margin-top:8%; margin-left:5%; display:none\" id=\"divform\">\r\n");
      out.write("\r\n");
      out.write("<label for=\"ename\" style=\"margin-button:5%\">Employee Name: </label>\r\n");
      out.write("<input type=\"text\" name=\"ename\" id=\"ename\"style=\"margin-button:5% ; width:40%;height:8%\" />\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<label for=\"eaddress\" style=\"margin-button:5%\">Employee Address: </label>\r\n");
      out.write("<input type=\"text\" name=\"eaddress\" id=\"eaddress\" style=\"margin-button:5%; width:40%;height:8%\" />\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<label for=\"ephone\" style=\"margin-button:5%\">Employee Phone Number: </label>\r\n");
      out.write("<input type=\"text\" name=\"ephone\" id=\"ephone\" style=\"margin-button:5%; width:40%;height:8%\" />\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<label for=\"eage\"style=\"margin-button:5%\" >Employee Age: </label>\r\n");
      out.write("<input type=\"text\" name=\"eage\" id=\"eage\" style=\"margin-button:5%; width:40%;height:8%\" />\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" name=\"save\" id=\"save\" style=\"margin-button:5%; width:40%;height:8%\" value=\"save\" onclick=\"onSave()\"/>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("var id = 3;\r\n");
      out.write("function onSave()\r\n");
      out.write("{   \r\n");
      out.write("    alert(\"----------onsave---------\");\r\n");
      out.write("\t\r\n");
      out.write("\tvar name = document.getElementById(\"ename\").value;\r\n");
      out.write("\tvar address = document.getElementById(\"eaddress\").value;\r\n");
      out.write("\tvar phone = document.getElementById(\"ephone\").value;\r\n");
      out.write("\tvar age = document.getElementById(\"eage\").value;\r\n");
      out.write("\tvar table  = document.getElementById(\"table\");\r\n");
      out.write("\t\r\n");
      out.write("\ttable.innerHTML += \"<TR><td><input type='radio' class='radio' name='0'/></td><TD>\"+id+\"</TD><TD>\"+ name +\"</TD><TD>\" + address + \"</TD><TD>\" + phone + \"</TD><TD>\" + age + \"</TD></TR>\";\r\n");
      out.write("\tid = id + 1;\r\n");
      out.write("\tvar form      = document.getElementById(\"divform\");\r\n");
      out.write("\tform.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("function onChange(){\r\n");
      out.write("var radioButtons = document.querySelectorAll('.radio');\r\n");
      out.write("\r\n");
      out.write("        for (var i = 0; i < radioButtons.length; i++) {\r\n");
      out.write("            \r\n");
      out.write("                if (radioButtons[i].checked == true) {\r\n");
      out.write("                    var parent = radioButtons[i].parentNode;\r\n");
      out.write("                    parent.style.backgroundColor = \"red\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                   }\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("function onModify(){\r\n");
      out.write("var form      = document.getElementById(\"divform\");\r\n");
      out.write("\tform.style.display = \"inline-block\";\r\n");
      out.write("var radioButtons = document.querySelectorAll('.radio');\r\n");
      out.write("        for (var i = 0; i < radioButtons.length; i++) {\r\n");
      out.write("            \r\n");
      out.write("                if (radioButtons[i].checked == true) {\r\n");
      out.write("                    var parent = radioButtons[i].parentNode;\r\n");
      out.write("                    var parent2 = parent.parentNode;\r\n");
      out.write("\t\t\t\t\tconst child = parent2.children;\r\n");
      out.write("\t\t\t\t\tvar name = child[2].innerHTML;\r\n");
      out.write("\t\t\t\t\tvar address = child[3].innerHTML;\r\n");
      out.write("\t\t\t\t\tvar phone = child[4].innerHTML;\r\n");
      out.write("\t\t\t\t\tvar age = child[4].innerHTML;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar fname = document.getElementById(\"ename\");\r\n");
      out.write("\t                var faddress = document.getElementById(\"eaddress\");\r\n");
      out.write("\t                var fphone = document.getElementById(\"ephone\");\r\n");
      out.write("\t                var fage = document.getElementById(\"eage\");\r\n");
      out.write("\t\t\t\t\tfname.value = name;\r\n");
      out.write("\t\t\t\t\tfaddress.value = address;\r\n");
      out.write("\t\t\t\t\tfphone.value = phone;\r\n");
      out.write("\t\t\t\t\tfage.value = age;\r\n");
      out.write("\t\t\t\t\tparent2.style.display=\"none\";\r\n");
      out.write("\t          }\t\r\n");
      out.write("}       \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
